### PR TITLE
Django 4 support

### PR DESCRIPTION
**Pull request by aringot**
Building up on PR https://github.com/thomst/django-more-admin-filters/pull/18 by [artemiydruzhinin](https://github.com/artemiydruzhinin) (I have no write access on this branch), I [added tox and travis config for Django 4.0.x](https://github.com/thomst/django-more-admin-filters/commit/0021e3b8bee94f86fa6bf7a6238d20152d900dd3). Not too sure how to test that locally.

Should also fix issue https://github.com/thomst/django-more-admin-filters/issues/16

### CODE REVIEW

**Comment by aringot** [comment]
@thomst any chance you can review this?

**Comment by CharlesFr** [comment]
I'm looking for 4.x support - can this be merged?

**Comment by Lotfull** [comment]
Please, merge Django 4+ support PR

**Comment by areski** [comment]
@aringot I updated your PR to support 4.1 -> https://github.com/thomst/django-more-admin-filters/pull/22

**Comment by thomst** [comment]
@aringot @areski Thank you for your contribution. I know merged the PR#22 which make this one obsolete.

**Pull request closed without merging**
